// Generated by gir (https://github.com/gtk-rs/gir @ 9aa16ead87e1)
// from /home/ellorent/Documents/cnv/upstream/gir-files (@ b8b90867ab35)
// from ../gir-files (@ ???)
// DO NOT EDIT

#[cfg(not(feature = "dox"))]
use std::process;

#[cfg(feature = "dox")]
fn main() {} // prevent linking libraries to avoid documentation failure

#[cfg(not(feature = "dox"))]
fn main() {
    if let Err(s) = system_deps::Config::new().probe() {
        println!("cargo:warning={}", s);
        process::exit(1);
    }
}
